# .github/workflows/test-review-checklist.yml

name: 'Generate Post-Acceptance Checklist'

# This workflow will be triggered when a comment is created on a pull request or issue.
on:
  issue_comment:
    types: [created]

# We need permissions to update issue comments.
permissions:
  issues: write

jobs:
  add-basics-checklist:
    # This job will only run if the comment body contains the '/generate-review-checklist' command.
    if: startsWith(github.event.comment.body, '/generate-post-acceptance-checklist') && contains(fromJSON('["MEMBER", "OWNER"]'), github.event.comment.author_association)
    runs-on: ubuntu-latest
    steps:
      - name: Add Basics Checklist
        uses: actions/github-script@v7
        with:
          script: |
            // This script uses the GitHub REST API to update the comment.
            // The `github.rest.issues.updateComment` method takes the
            // owner, repo, comment_id, and the new body as arguments.

            // Define the new checklist in GitHub-flavored Markdown.
            const reviewChecklist = `
            # Post-acceptance checklist - For the FIT coordinator

            - [ ] Add software to FIT test site and have author verify it looks as expected
            - [ ] If R package, add to the FIT R universe
            - [ ] Add to FIT production site and share production page
            - [ ] Close review issue

            `;

            // Call the GitHub API to update the comment with the new checklist.
            try {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                body: reviewChecklist,
              });
              console.log('Successfully updated comment with review checklist.');
            } catch (error) {
              console.error('Failed to update comment:', error);
            }
